### ISSUE TITLE
Ancestral CN profiles and CNA history

### ISSUE THREAD

**Issue by anlo328** [raphael-group/lazac-copy-number#1]
Dear lazac team,

I managed to get your tool running on a small dataset of about 10 single cells. Eventually, I rooted the tree on an (almost) non-aberrant normal cell. 

What I'm interested in now would be to understand the inferred CNA history, i.e., which changes happened on the respective early and late branches of the tree. What I would need for this are the ancestral CN profiles, i.e., the tree nodes which are not leaves and have been inferred by lazac, but I can't seem to find any functionality to extract them. If I understand the method correctly, this information _should_ be somewhere after successful tree building, right?

Thanks and best wishes!

**Comment by schmidt73** [comment]
Yes, you are definitely correct that this information _should_ be somewhere after successful tree labeling. Indeed, it is, but it may take me a little bit of time to properly extract for you.

Do you have a time frame for needing this functionality? I will be able to take a crack at it this week. Please reach out by email (henri.schmidt@princeton.edu) if you need any more assistance. I'm happy to help.

**Comment by anlo328** [comment]
Thanks for the surprisingly swift reply! 

It is actually somewhat urgent, but this isn't your problem. An acceptable solution for me would also be to just visualise the observed CN profiles by the dendrogram given by lazac, and for that I should already have all I need.

If you would manage to provide the functionality of outputting the ancestal CN profiles, that would be so great though. From that "inferring the edge labels", so basically doing `child node - ancestral node = gained changes`, that I should be able to manage myself. 

Thanks again and have a nice weekend soon.

**Comment by schmidt73** [comment]
Great, I'll close this issue for now, but will put outputting ancestral profiles on my todo list.

Have a nice weekend.

**Comment by schmidt73** [comment]
@anlo328 as an update, we now include the inferred CN profiles in the output. An important note is that the inferred CN profiles are not uniquely determined, since there are potentially many optimal ancestral labelings, even in simple cases. 

Another caveat is that the ancestral labeling procedure solves a relaxation of the ZCNT small parsimony problem, not solving it exactly. To fix this, we have an approximation algorithm which is described in our paper, but have not implemented it in code. If upon testing, higher quality solutions are needed, we could implement this approximation algorithm.

**Comment by anlo328** [comment]
Thanks a lot for your continued effort. Me and my colleague have tried to work with the extended output, but unfortunately encountered some ambiguities, which my colleague @huy29433 will describe in another issue.
